apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-deployer
  namespace: hola-mundo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-deployer-role
  namespace: hola-mundo
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-deployer-binding
  namespace: hola-mundo
subjects:
  - kind: ServiceAccount
    name: pipeline-deployer
    namespace: hola-mundo
roleRef:
  kind: Role
  name: pipeline-deployer-role
  apiGroup: rbac.authorization.k8s.io
