server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy hacia el backend (Web API) dentro del cluster
    location /api/ {
        proxy_pass http://backend-service:3000/api/;
    }
}
