apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: pipeline-frontend-run-
  namespace: hola-mundo
spec:
  taskRunTemplate:
    serviceAccountName: pipeline-deployer
  pipelineRef:
    name: pipeline-frontend
  params:
    - name: GIT_REPO_URL
      value: "https://github.com/jojoahector19/hola-mundo-devops.git"
    - name: GIT_REVISION
      value: "main"
    - name: IMAGE
      value: "k3d-registry.localhost:5000/hola-mundo-frontend:latest"
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
