apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: hola-mundo
type: Opaque
stringData:
  POSTGRES_DB: holamundo
  POSTGRES_USER: holamundo_user
  POSTGRES_PASSWORD: change_me_123
